on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 3
      - name: Run-Script
        uses: stefanzweifel/git-auto-commit-action@v4
        run: |
          pip install yq
          chmod +x ./update-version.sh
          ./update-version.sh
